### ISSUE TITLE
Dist diff on build

### ISSUE THREAD

**Issue by sfinnman** [vic1707/GHA-combine-PRs#10]
Tried building this repository locally using the versions listed in the package.json and ended up with a diff to the dist/index.js

Because the dist is minified, it's hard to verify that the contents of the distributed javascript are correct and built from the source in the repository.

Perhaps a way to remedy this is to provide a simple container to build the project, such that the output dist is stable and can be verified by building from local?

This would help me sleep at night, since this package is relatively new :)

**Comment by vic1707** [comment]
Hello,

Thanks for the suggestion, I have to say I'm a little surprised to see a diff in the `dist/index.js` file since I checked less than 5 days ago and there wasn't any (I fully understand you're concern).

A better solution could be to get a Github action to build and deploy the action automatically but couldn't find a satisfying solution atm (still looking for one).

I'm tying to find what caused this diff 🤔. 
Once I find what caused it I'll be happy to update the dist file 😉

**Comment by vic1707** [comment]
the commit 703e295f0469f96f678fc4ff5bafacf8c5bd754e seems to be the culprit or at least it's the first commit where the `dist/index.js` changes.

I'll deploy the new `index.js` in asap you should be able to get the same if you build locally 👍 

I'll look deeper into CI for actions deployment
